### ISSUE TITLE
Update documentation if running on Windows command line to use double quote " instead of single quote ' for database url

### ISSUE THREAD

**Issue by yrfu** [theseus-rs/rsql#185]
**What steps will reproduce the bug?**
1. Download msi binaries for Windows and install
2. run command using single quote ' as per documentation
3. run the command again using double quotes " for database url 

**What happens?**
What's not working
C:\Program Files\rsql_cli\bin>rsql --url 'mysql://root:secrets!@127.0.0.1:3306/mysql' -- "SELECT version();"
Error: relative URL without a base

What's working
C:\Program Files\rsql_cli\bin>rsql --url "mysql://root:secrets!@127.0.0.1:3306/mysql" -- "SELECT version();"
     version()
-------------------
 8.0.39-community
1 row (1.7841ms)

**What did you expect to happen instead?**
     version()
-------------------
 8.0.39-community
1 row (1.7841ms)

**How did you install `rsql`?**
Via Github release msi installer for Windows

### Information about your environment

* rsql version: rsql/0.13.11 Windows/10.0.22631/x86_64
* Database and version: MySQL 8.0.39
* Operating system: Windows 11

**Comment by brianheineman** [comment]
@yrfu thank you for reporting the issue.  This should be addressed by #187
