### ISSUE TITLE
can u write some guide or examples about rsql_drivers?

### ISSUE THREAD

**Issue by xurwxj** [theseus-rs/rsql#222]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add guide or examples in rsql_drivers.
Examples with db connection share will be great.

**Describe alternatives you've considered**

**Additional context**

**Comment by brianheineman** [comment]
Hello @xurwxj, thank you for your request.  I added a simple example in #239 that illustrates how to create a connection using the `rsql_drivers` crate.  These drivers do not currently support parameter binding, so they should only be used where the inputs are trusted.
