### ISSUE TITLE
postgres: incorrect column order for indexes in .describe [table]

### ISSUE THREAD

**Issue by alexyarovoy** [theseus-rs/rsql#241]
**What steps will reproduce the bug?**

run .describe for table with indexes

**What happens?**

columns for indexes are shown in alphabetical order

**What did you expect to happen instead?**

columns would be shown in the order they were set during index creation

**How did you install `rsql`?**

cargo install rsql_cli

### Information about your environment

* rsql version: rsql/0.15.0 Mac-OS/15.1.0/arm64
* Database and version: PostgreSQL 13
* Operating system: Mac-OS 15.1.0

**Comment by brianheineman** [comment]
@alexyarovoy Thank you for reporting the issue.  I created PR #242 to correct the column index ordering.

**Comment by brianheineman** [comment]
@alexyarovoy the fix for this was released in [0.15.1](https://github.com/theseus-rs/rsql/releases/tag/v0.15.1)
